sudo: false

language: python

python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install codecov
  - pip install pandas
  - pip install cairosvg
  - python ./python/setup.py install
  
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - coverage run python/swagbag/tests/test_swag.py

after_success:
  - codecov
